### ISSUE TITLE
Beat numbers and anacrustic measures

### ISSUE THREAD

**Issue by MarkGotham** [DCMLab/ABC#14]
Hi all,

I’ve noticed that a lot of the measure and beat number errors in the ABC seem to be inherited from issues in MuseScore.
1.
For a start, MuseScore (versions 2 and 3) count anacrustic (‘pick up’) measures from ‘1’ (i.e. not 0).
2.
MuseScore 2 has additional problems with counting beat numbers thereafter in some anacrustic works (I have no straightforward summary of that problem, I’m afraid).
3.
MuseScore 3 seems to have fixed those (item 2) counting errors except for in 2/2 where it counts both the second quarter and the second half notes as ‘2’. Thus, the four quarters of a 2/2 measures have beats ‘1, 2, 2, 3’.

I’ll raise this with MuseScore, but it’s worth you guys knowing now if you’re preparing ABC versions 1, 2, 3(!)

**Comment by fabianmoss** [comment]
Hi Mark,
thanks for bringing this to our attention. Indeed, the transition to MuseScore 3 seems to solve this problem largely and we will be working on the transition at some point. It would be great if you could mention the weird 2/2 behavior to the MuseScore developers. I can't imagine that this is desired.
