### ISSUE TITLE
Wrong beat number and duration

### ISSUE THREAD

**Issue by lancioni** [DCMLab/ABC#17]
I found a typo in op. 127 No. 12 1st movement, line 203 of the tsv file: beat of chord I is given as 5.0 (of course impossible in a 3/4) measure instead than 2.0; as a consequence, duration is -1.0 instead than 2.0. The same error is automatically reproduced in all_annotations.tsv, also line 203.

The mscx file looks right.

**Comment by johentsch** [comment]
Thanks for letting us know! Actually there are more of these errors in the dataset. We are currently preparing version 2 with the scores converted to MuseScore 3 and with more plentiful tables added. You can check it out in the corresponding sidebranch https://github.com/DCMLab/ABC/tree/v2 (in your local clone, do ``git checkout v2`` to access). These errors should not occur anymore and the scores should be overall more correct.

**Comment by lancioni** [comment]
Thank you! I'm checking it out presently.

Giuliano


Inviato da smartphone Samsung Galaxy.



-------- Messaggio originale --------
Da: Johannes Hentschel <notifications@github.com>
Data: 26/09/20 12:36 (GMT+01:00)
A: DCMLab/ABC <ABC@noreply.github.com>
Cc: Giuliano Lancioni <giuliano.lancioni@uniroma3.it>, Author <author@noreply.github.com>
Oggetto: Re: [DCMLab/ABC] Wrong beat number and duration (#17)


Thanks for letting us know! Actually there are more of these errors in the dataset. We are currently preparing version 2 with the scores converted to MuseScore 3 and with more plentiful tables added. You can check it out in the corresponding sidebranch https://github.com/DCMLab/ABC/tree/v2 (in your local clone, do git checkout v2 to access). These errors should not occur anymore and the scores should be overall more correct.
