### ISSUE TITLE
op18_no1_mov2 rhythm issues

### ISSUE THREAD

**Issue by craigsapp** [DCMLab/ABC#18]
Measure 92, Violin 1:

The F4, G4 at the end of the Violin 1 part are in a two-note triplet.  This causes the first layer of music on the staff to be underfilled.  Musescore incorrectly inserts a dotted 16th note (in gray).  The tupletness of the notes should be removed.

<img width="393" alt="Screen Shot 2020-10-06 at 9 51 35 PM" src="https://user-images.githubusercontent.com/3487289/95293641-aed76d80-0828-11eb-978b-be5b8a8430fc.png">

------------------

Measure 101, Cello, third beat D4 should be an eighth note rather than a dotted eight note.  This causes the Cello part to be overfilled, and Musescore adds 16th note rests in gray to the end of the other parts:

<img width="830" alt="Screen Shot 2020-10-06 at 11 11 18 PM" src="https://user-images.githubusercontent.com/3487289/95294045-6ec4ba80-0829-11eb-8a9f-355a6d085681.png">

----------------------------

Measure 87, Violin 1 part is underfilled, with Musescore adding an eighth rest (in gray).  The problem is that beat 2 (D5) needs an augmentation dot to convert from a quarter note into a dotted quarter note:

<img width="457" alt="Screen Shot 2020-10-06 at 11 15 13 PM" src="https://user-images.githubusercontent.com/3487289/95294247-cbc07080-0829-11eb-9317-5b9e8b47402e.png">

**Comment by johentsch** [comment]
As for (#11) I would like to point you to the corrected scores in MuseScore 3 format which are currently sitting in the development branch  https://github.com/DCMLab/ABC/tree/v2 Feel free to reopen the issue if it doesn't solve the issue.
