### ISSUE TITLE
n09op59-3_02 measure 143 voicing problem

### ISSUE THREAD

**Issue by craigsapp** [DCMLab/ABC#19]
In measure 143 of `n09op59-3_02.mscx` (`v2` branch), there is a voicing problem in the 1st violin that is not visible in the notation:

<img width="286" alt="Screen Shot 2020-10-07 at 7 23 30 AM" src="https://user-images.githubusercontent.com/3487289/95344336-6478df80-086e-11eb-8479-42049c1e16d9.png">

Selecting the measure should highlight the problem:

<img width="287" alt="Screen Shot 2020-10-07 at 7 39 55 AM" src="https://user-images.githubusercontent.com/3487289/95346142-5deb6780-0870-11eb-8e17-120c812736d5.png">

The problem is on the second beat for the E5 notes, where both notes have a dotted quarter duration.  Only the stem-up E5 should have an augmentation dot, while the stem-down note should not have a dot so that the following D5 remains in the same voice as the down-stem E5.

Removing the augmentation dot on the E5 in the second voice and moving the D5 from the third to second voice produces a more semantic encoding:

<img width="268" alt="Screen Shot 2020-10-07 at 7 51 46 AM" src="https://user-images.githubusercontent.com/3487289/95347777-2087d980-0872-11eb-99df-24ec9ee2d8ee.png">

(The slur needs to be adjusted between the two notes as well).

If you want the two E's to share the same notehead (which looks better as will be visually similar to the original view), the quarter note E5 could be given a negative horizontal offset (Chord: x &rarr; -2.50sp) in the inspector panel:

<img width="258" alt="Screen Shot 2020-10-07 at 7 58 00 AM" src="https://user-images.githubusercontent.com/3487289/95348568-06023000-0873-11eb-8242-0d6ea321ddb5.png">

**Comment by johentsch** [comment]
Thank you very much for this very precise observation. Since you seem to have fixed for yourself already, would you be willing to share your solution via a PR?

**Comment by johentsch** [comment]
Thank you very much!
