### ISSUE TITLE
Hidden rests in Op.18 No.1 - IV

### ISSUE THREAD

**Issue by napulen** [DCMLab/ABC#22]
There are several hidden rests in this score. The most problematic is this one on `m296`, where there is also an overflown measure:

![image](https://user-images.githubusercontent.com/7258463/112634524-169e6680-8e11-11eb-8115-19f341bb05c6.png)

These rests are confusing when obtaining the position of the notes from the MusicXML score.

**Comment by napulen** [comment]
I have only seen this issue in this particular movement.

**Comment by johentsch** [comment]
Hi Néstor, 
You may want to checkout [branch v2](https://github.com/DCMLab/ABC/tree/v2) which has corrected scores for the next release.

**Comment by napulen** [comment]
Thanks @johentsch!
