### ISSUE TITLE
Feature request: offsets in quarter notes in notes tsv files?

### ISSUE THREAD

**Issue by malcolmsailor** [DCMLab/ABC#28]
I have a question about the tsv files in the `notes` directory. I'm curious whether you would consider adding a column consisting of the onset time of each note in quarter notes. (E.g., if a note sounds on beat 3 of measure 2, where both measures are in 4/4, the onset time would be 6.) The onset time can be inferred from the mn and mn_onset columns, but it is not trivial to do so because previous measures may have had different time signatures. I will write myself a little script to do this if needs be, but if it would be a simple matter for you to add this based on your already existing code, perhaps it would be useful to people beyond just me?

**Comment by yrammos** [comment]
Hi @malcolmsailor, I vaguely recall us having entertained this possibility in the past and deciding against (@johentsch will remember better). You could bring this up on the [`ms3` parser repo](https://github.com/johentsch/ms3), since this is the component in the toolchain that would generate this information.

**Comment by johentsch** [comment]
Rather the opposite, the possibility is already part of the parser and continuous quarter note positions are planned to be default columns. Will add a preview to the v2 branch soon.

**Comment by johentsch** [comment]
Added the columns to the notes and harmonies on the new [v2_preview](https://github.com/DCMLab/ABC/tree/v2_preview) branch.

**Comment by yrammos** [comment]
Excellent, @johentsch.
