### ISSUE TITLE
op135_02 and first/second ending behavior

### ISSUE THREAD

**Issue by malcolmsailor** [DCMLab/ABC#31]
Almost at the end of op135_02, we have the following passage:

<img width="1060" alt="Screen Shot 2022-08-11 at 11 27 44 AM" src="https://user-images.githubusercontent.com/28103673/184171058-36002350-777b-4c7d-a5ad-2a665351dc5f.png">

As you can see, there is both a first and second ending notated.

In the v2_preview version of this file, these lines are

```
792	16.0	267	266	1/2	1/2	3/4	4	1		viio		F	I		viio	vii	o						o	0	0	5, 2, -1		5	5
		268	267	0	0	3/4	4	1	1	I\\		F	I		I	I						\\	M	0	0	0, 4, 1		0	0
		268	267	1/4	1/4	3/4	4	1	1	V2/IV		F	I		V2/IV	V		2		IV			Mm7	0	0	-2, 0, 4, 1		0	-2
		269	268	0	0	3/4	4	1	1	I\\		F	I		I	I						\\	M	0	0	0, 4, 1		0	0
		269	268	1/4	1/4	3/4	4	1	1	I		F	I		I	I							M	0	0	0, 4, 1		0	0
808	3.0	275	274	0	0	3/4	4	1		I\\		F	I		I	I						\\	M	0	0	0, 4, 1		0	0
```

The `quarterbeats` and `duration_qb` columns (first two columns) are empty for the first ending, which is what I expected.

However, they are also empty for the second ending, which I did not expect.

Note moreover that this means the viio harmony on the first line is given a duration of 16 when in fact its duration is only 1.

https://github.com/DCMLab/ABC/blob/v2_preview/harmonies/n16op135_02.tsv#L373

**Comment by johentsch** [comment]
Thanks for noticing. The second ending was encoded as a first ending. It is now fixed on v2 and v2_preview. For the latter, I generated the files with the current development version of ms3. The files from the `harmonies` folder can now be found in the `expanded` folder.
